### ISSUE TITLE
Range Expressions Are Not Properly Compiled

### ISSUE THREAD

**Issue by LinesPrower** [intellifactory/websharper#413] opened 2015-05-25 18:25 UTC
When the range is empty, execution of the corresponding JS code causes a "The input must be non-negative." exception.
Example: `[ for i in 0 .. -1 -> 42 ]`

Notes:
This bug only occurs in Client-Server applications, not in HTML applications.
WebSharper version: 3.1.6.156

**Comment by Tarmil** [comment] 2015-05-25 19:03
Duplicate of #412; this issue is fixed in the source and will be available in the next release.

**Closed by Tarmil** 2015-05-25 19:03 UTC
