### ISSUE TITLE
Class constructor causes crash

### ISSUE THREAD

**Issue by FilippoPolo** [intellifactory/websharper#757] opened 2017-09-04 18:13 UTC
This code:
```
type test_type (foo:string) =
  static let doStuff (a:string) = a+"."
  member x.foo = foo
let run_test_type () =
  let tt = new test_type ("foo")
  tt
```
After translation to JS, will cause a crash at runtime. The translated constructor is calling $cctor, which is undefined.

Tested on Zafir 4.0.187.90-beta10.

**Comment by Jand42** [comment] 2017-09-04 20:29
This is a duplicate of #753, fix will be released soon.

**Closed** 2017-09-04 21:37 UTC
Labels: released in Zafir.4.0.188.91-beta10
