### ISSUE TITLE
Cannot "run" Html Website project in VS

### ISSUE THREAD

**Issue by intellifactory-bb** [intellifactory/websharper#258] opened 2014-12-06 15:32 UTC
Without debugger (Ctrl+F5) - nothing happens. With debugger "cannot debug this project."

----------------------------------------
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/258
- Originally reported by: Anton Tayanovskyy
- Originally created at: 2014-07-03T15:47:14.841

**Comment by Tarmil** [comment] 2015-03-29 07:46
Duplicate of #235.

**Closed by Tarmil** 2015-03-29 07:46 UTC
Labels: bug, duplicate
