### ISSUE TITLE
Uncaught ReferenceError: <SomeNamespace> is not defined

### ISSUE THREAD

**Issue by amieres** [intellifactory/websharper#720] opened 2017-07-21 16:16 UTC
Previously the generated file WebServer.js looked like this: 
```
20  Rop=Global.Rop;
21  Result=Rop&&Rop.Result;
```
Now line 20 is gone and code fails with this error
WebServer.js:21 Uncaught ReferenceError: Rop is not defined
    at WebServer.js:21
```
Because the namespace Rop in file Common.js was not included because it was not used.

**Comment by Jand42** [comment] 2017-07-24 10:31
Thanks, duplicate of https://github.com/intellifactory/websharper/issues/719
Sorry for this, a new release with the fix is coming today

**Closed** 2017-07-26 07:54 UTC
Labels: released in Zafir.4.0.177.78-beta9
